#!/usr/bin/env bash

set -ex

PATH=/usr/local/share/.config/yarn/global/node_modules/.bin:$PATH

if [[ "$CIRCLE_BRANCH" != greenkeeper/* ]]; then
  #yarn
  # yarn check
  exit 0
fi

if [[ ! -z "$GIT_EMAIL" ]] & [[ ! -z "$GIT_USERNAME" ]]; then
  git config --global push.default simple
  git config --global user.email "$GIT_EMAIL"
  git config --global user.name "$GIT_USERNAME"
fi

if [[ ! -x "$(command -v greenkeeper-lockfile-update)" ]]; then
  yarn global add greenkeeper-lockfile@1
fi

CI_PULL_REQUEST=''
greenkeeper-lockfile-update
greenkeeper-shrinkwrap-update
yarn
greenkeeper-lockfile-upload
greenkeeper-shrinkwrap-upload
